-- AlterTable
ALTER TABLE "BotSetting" ADD COLUMN IF NOT EXISTS "onboardingStep" TEXT NOT NULL DEFAULT '1';
ALTER TABLE "BotSetting" ADD COLUMN IF NOT EXISTS "onboardingCompletedAt" TIMESTAMP(3);
ALTER TABLE "BotSetting" ADD COLUMN IF NOT EXISTS "embedLiveAt" TIMESTAMP(3);
ALTER TABLE "BotSetting" ADD COLUMN IF NOT EXISTS "widgetPrimaryColor" TEXT DEFAULT '#008060';
ALTER TABLE "BotSetting" ADD COLUMN IF NOT EXISTS "widgetPosition" TEXT DEFAULT 'bottom-right';
ALTER TABLE "BotSetting" ADD COLUMN IF NOT EXISTS "welcomeMessage" TEXT;
ALTER TABLE "BotSetting" ADD COLUMN IF NOT EXISTS "welcomeMessageI18n" JSONB;
ALTER TABLE "BotSetting" ADD COLUMN IF NOT EXISTS "syncProductsEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "BotSetting" ADD COLUMN IF NOT EXISTS "syncOrdersEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "BotSetting" ADD COLUMN IF NOT EXISTS "syncCustomersEnabled" BOOLEAN NOT NULL DEFAULT true;
