-- Runs only on first postgres init
CREATE USER drsell_app WITH PASSWORD 'Dr$7gK_m9Qx!vR2p#Lw8nTz@Y4uH' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE drsell OWNER drsell_app;
\c drsell
GRANT ALL ON SCHEMA public TO drsell_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO drsell_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO drsell_app;
